name: Run Tests

on: [push, workflow_dispatch, pull_request]

jobs:
  run-tests:
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v1

      - name: Run Tests
        run: |
          xcodebuild -scheme Twift -resultBundlePath TestResults -destination 'platform=OS X,arch=x86_64' clean test

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: success() || failure()

